services:
  web:
    build: .
    ports:
      - "8089:8089"
    command: uvicorn main:app --host 0.0.0.0 --port 8089
    environment:
      - REDIS_URL=redis://redis:6379/0
      - REDIS_PASSWORD=your_password
    depends_on:
      - redis

  worker:
    build: .
    command: rq worker
    environment:
      - REDIS_URL=redis://redis:6379/0
      - REDIS_PASSWORD=your_password
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  api:
    # ... your API service configuration ...
    environment:
      - REDIS_HOST=redis  # When using Docker, the host should be the service name
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
