
services:
  api:
    build: .
    ports:
      - "8089:8089"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
      - worker

  worker:
    build: 
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 4G  # Set maximum memory limit
        reservations:
          memory: 2G  # Set minimum memory reservation
    environment:
      - REDIS_HOST=redis
    command: rq worker --url redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"